[package]
name = "neo3d-sys"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["cdylib"]

[dependencies]
anyhow = "1.0.75"
glfw = "0.53.0"
jni = "0.21.1"
lazy_static = "1.4.0"
pollster = "0.3.0"
raw-window-handle = "0.5.2"
wgpu = "0.17.0"
